openapi: 3.0.1
info:
  contact:
    email: team-expense-core@pleo.io
  description: Tax Codes OpenAPI definitions
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://pleo.io/terms/
  title: Tax Code API
  version: 42.14.0
servers:
- description: Production server
  url: https://external.pleo.io
- description: Staging server
  url: https://external.staging.pleo.io
security:
- bearerAuth: []
tags:
- description: Tax Codes API
  name: tax-codes
paths:
  /v0/tax-codes:
    post:
      operationId: createTaxCode
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/TaxCodeCreateUpdateModel'
        required: true
      responses:
        default:
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/DataResponseTaxCodeModel'
          description: default response
      summary: Create a new tax code
      tags:
      - tax-codes
  /v0/tax-codes/{taxCodeId}:
    delete:
      operationId: deleteTaxCode
      parameters:
      - explode: false
        in: path
        name: taxCodeId
        required: true
        schema:
          description: Tax code ID to delete
          format: uuid
          type: string
        style: simple
      responses:
        default:
          content:
            application/json;charset=UTF-8: {}
          description: default response
      summary: Delete an tax code
      tags:
      - tax-codes
    get:
      operationId: getTaxCode
      parameters:
      - explode: false
        in: path
        name: taxCodeId
        required: true
        schema:
          description: Tax code ID to fetch
          format: uuid
          type: string
        style: simple
      responses:
        default:
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/DataResponseTaxCodeModel'
          description: default response
      summary: Returns a given tax code
      tags:
      - tax-codes
    put:
      operationId: updateTaxCode
      parameters:
      - explode: false
        in: path
        name: taxCodeId
        required: true
        schema:
          description: Tax code ID to update
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/TaxCodeCreateUpdateModel'
        required: true
      responses:
        default:
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/DataResponseTaxCodeModel'
          description: default response
      summary: Update an tax code
      tags:
      - tax-codes
  /v0/tax-codes:search:
    post:
      operationId: getTaxCodes
      parameters:
      - explode: true
        in: query
        name: company_id
        required: false
        schema:
          description: Fetch a list of tax codes for a given company
          format: uuid
          type: string
        style: form
      - description: "Lower bound of the page of data to return (cannot be used together\
          \ with [after] or [offset])"
        explode: true
        in: query
        name: before
        required: false
        schema:
          type: string
        style: form
      - description: "Upper bound of the page of data to return (cannot be used together\
          \ with [before] or [offset])"
        explode: true
        in: query
        name: after
        required: false
        schema:
          type: string
        style: form
      - description: "Offset of the page of data to return (cannot be used together\
          \ with [before] or [after])"
        explode: true
        in: query
        name: offset
        required: false
        schema:
          format: int64
          type: integer
        style: form
      - description: The maximum amount of items to return
        explode: true
        in: query
        name: limit
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - description: The keys to sort the results by
        explode: true
        in: query
        name: sorting_keys
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "The order to sort the results by. Must be the same length as\
          \ [sortingKeys]; one order per key"
        explode: true
        in: query
        name: sorting_order
        required: false
        schema:
          items:
            $ref: '#/components/schemas/PageOrder'
          type: array
        style: form
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/TaxCodeSearchRequest'
      responses:
        default:
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/CursorPaginatedResponseTaxCodeModel'
          description: default response
      summary: Returns a list of tax codes
      tags:
      - tax-codes
components:
  schemas:
    CursorPageCurrentRequestInfo:
      example:
        sortingKeys:
        - sortingKeys
        - sortingKeys
        sortingOrder:
        - null
        - null
        offset: 6
        before: before
        limit: 0
        after: after
        parameters:
          key:
          - parameters
          - parameters
      properties:
        after:
          type: string
        before:
          type: string
        limit:
          format: int32
          type: integer
        offset:
          format: int64
          type: integer
        parameters:
          additionalProperties:
            items:
              type: string
            type: array
          type: object
        sortingKeys:
          items:
            type: string
          type: array
        sortingOrder:
          items:
            $ref: '#/components/schemas/PageOrder'
          type: array
      required:
      - parameters
      type: object
    CursorPageInfo:
      example:
        currentRequestPagination:
          sortingKeys:
          - sortingKeys
          - sortingKeys
          sortingOrder:
          - null
          - null
          offset: 6
          before: before
          limit: 0
          after: after
          parameters:
            key:
            - parameters
            - parameters
        total: 1
        hasNextPage: true
        hasPreviousPage: true
        endCursor: endCursor
        startCursor: startCursor
      properties:
        currentRequestPagination:
          $ref: '#/components/schemas/CursorPageCurrentRequestInfo'
        endCursor:
          type: string
        hasNextPage:
          type: boolean
        hasPreviousPage:
          type: boolean
        startCursor:
          type: string
        total:
          format: int64
          type: integer
      required:
      - currentRequestPagination
      - hasNextPage
      - hasPreviousPage
      type: object
    CursorPaginatedResponseTaxCodeModel:
      example:
        pagination:
          currentRequestPagination:
            sortingKeys:
            - sortingKeys
            - sortingKeys
            sortingOrder:
            - null
            - null
            offset: 6
            before: before
            limit: 0
            after: after
            parameters:
              key:
              - parameters
              - parameters
          total: 1
          hasNextPage: true
          hasPreviousPage: true
          endCursor: endCursor
          startCursor: startCursor
        data:
        - archived: true
          createdAt: 2000-01-23T04:56:07.000+00:00
          companyId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          code: "01"
          ingoingTaxAccount: ingoingTaxAccount
          rate: 0.8008281904610115
          name: Standardmoms (25 %)
          accountingIntegrationSystem: accountingIntegrationSystem
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          outgoingTaxAccount: outgoingTaxAccount
          type: inclusive
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - archived: true
          createdAt: 2000-01-23T04:56:07.000+00:00
          companyId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          code: "01"
          ingoingTaxAccount: ingoingTaxAccount
          rate: 0.8008281904610115
          name: Standardmoms (25 %)
          accountingIntegrationSystem: accountingIntegrationSystem
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          outgoingTaxAccount: outgoingTaxAccount
          type: inclusive
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        data:
          items:
            $ref: '#/components/schemas/TaxCodeModel'
          type: array
        pagination:
          $ref: '#/components/schemas/CursorPageInfo'
      required:
      - data
      - pagination
      type: object
    DataResponseTaxCodeModel:
      example:
        data:
          archived: true
          createdAt: 2000-01-23T04:56:07.000+00:00
          companyId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          code: "01"
          ingoingTaxAccount: ingoingTaxAccount
          rate: 0.8008281904610115
          name: Standardmoms (25 %)
          accountingIntegrationSystem: accountingIntegrationSystem
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          outgoingTaxAccount: outgoingTaxAccount
          type: inclusive
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        data:
          $ref: '#/components/schemas/TaxCodeModel'
      required:
      - data
      type: object
    PageOrder:
      enum:
      - ASC
      - ASC_NULLS_FIRST
      - ASC_NULLS_LAST
      - DESC
      - DESC_NULLS_FIRST
      - DESC_NULLS_LAST
      type: string
    TaxCodeCreateUpdateModel:
      example:
        archived: true
        companyId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        code: "01"
        ingoingTaxAccount: ingoingTaxAccount
        rate: 0.8008281904610115
        name: Standardmoms (25 %)
        outgoingTaxAccount: outgoingTaxAccount
        type: inclusive
      properties:
        archived:
          description: "Boolean flag used to archive or unarchive a category (when\
            \ set to true, account is not visible or usable on the platform)"
          type: boolean
        code:
          description: The accounting system's internal identifier of the tax code
          example: "01"
          nullable: true
          type: string
        companyId:
          description: Company ID the tax code is being created/updated for
          format: uuid
          type: string
        ingoingTaxAccount:
          description: Ingoing tax account usually used to account for reverse VAT
          nullable: true
          type: string
        name:
          description: Name of the tax code
          example: Standardmoms (25 %)
          type: string
        outgoingTaxAccount:
          description: Outgoing tax account usually used to account for reverse VAT
          nullable: true
          type: string
        rate:
          description: Percentage rate applied for this tax code (This is represented
            in decimals and not the percentage. e.g. 20% tax rate would be 0.20)
          type: number
        type:
          description: Classification of this tax code
          enum:
          - inclusive
          - exclusive
          - reverse
          type: string
      required:
      - archived
      - companyId
      - name
      - rate
      - type
      type: object
    TaxCodeModel:
      example:
        archived: true
        createdAt: 2000-01-23T04:56:07.000+00:00
        companyId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        code: "01"
        ingoingTaxAccount: ingoingTaxAccount
        rate: 0.8008281904610115
        name: Standardmoms (25 %)
        accountingIntegrationSystem: accountingIntegrationSystem
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        outgoingTaxAccount: outgoingTaxAccount
        type: inclusive
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        accountingIntegrationSystem:
          description: Accounting integration system
          nullable: true
          type: string
        archived:
          description: "Boolean flag used to archive or unarchive an account (when\
            \ set to true, account is not visible or usable on the platform)"
          type: boolean
        code:
          description: The accounting system's internal identifier of the tax code
          example: "01"
          nullable: true
          type: string
        companyId:
          description: The Pleo unique identifier of the company the tax code belongs
            to
          format: uuid
          type: string
        createdAt:
          description: Date and time the tax code was created
          format: date-time
          pattern: YYYY-MM-DDTHH:mi:ssZ
          type: string
        id:
          description: The unique identifier generated by Pleo for the tax code
          format: uuid
          type: string
        ingoingTaxAccount:
          description: Ingoing tax account usually used to account for reverse VAT
          nullable: true
          type: string
        name:
          description: Name of the tax code
          example: Standardmoms (25 %)
          type: string
        outgoingTaxAccount:
          description: Outgoing tax account usually used to account for reverse VAT
          nullable: true
          type: string
        rate:
          description: Percentage rate applied for this tax code (This is represented
            in decimals and not the percentage. e.g. 20% tax rate would be 0.20)
          type: number
        type:
          description: Classification of this tax code
          enum:
          - inclusive
          - exclusive
          - reverse
          type: string
        updatedAt:
          description: Date and time the tax code was last updated
          format: date-time
          pattern: YYYY-MM-DDTHH:mi:ssZ
          type: string
      required:
      - archived
      - companyId
      - createdAt
      - id
      - name
      - rate
      - type
      - updatedAt
      type: object
    TaxCodeSearchRequest:
      example:
        archived: true
        type: inclusive
        taxCodeIds:
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        archived:
          description: "If set to true will only return tax codes that have been archived,\
            \ if set to false will only return tax codes that have not been archived.\
            \ By default,both archived and non-archived tax codes will be returned."
          type: boolean
        taxCodeIds:
          description: Useful for fetching a list of tax codes given a specific list
            of IDs.
          items:
            description: Useful for fetching a list of tax codes given a specific
              list of IDs.
            format: uuid
            type: string
          type: array
          uniqueItems: true
        type:
          description: Classification of the tax codes to fetch
          enum:
          - inclusive
          - exclusive
          - reverse
          type: string
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
x-readme:
  explorer-enabled: true
  proxy-enabled: true
